function createCollisionClasses()
    world:addCollisionClass('Player')
    world:addCollisionClass('Enemy')
    world:addCollisionClass('Boss')
    world:addCollisionClass('Bullet')
    world:addCollisionClass('Wall')
    world:addCollisionClass('Coin', {ignores = {'Enemy', 'Boss'}})
    world:addCollisionClass('Food', {ignores = {'Enemy', 'Boss'}})
    world:addCollisionClass('Book', {ignores = {'Enemy', 'Boss'}})
    world:addCollisionClass('Npc')
    world:addCollisionClass('Transitions')
    world:addCollisionClass('Dialogues')
end